apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: 1-fantastic-bear-watcher
spec:
  template:
    serviceAccountName: sa-argo-workflow
  resource:
    1-fantastic-bear-succeeded:
      namespace: argo-workflows
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD
      filter:
        labels:
          - key: workflows.argoproj.io/phase
            operation: "=="
            value: "Succeeded"
        prefix: 1-fantastic-bear
        afterStart: false
#      eventTypes:
#        - UPDATE
#      filter:
#        fields:
#          - key: metadata.name
#            operation: ==
#            value: 1-fantastic-bear
#          - key: status.phase
#            operation: ==
#            value: Succeeded
