apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: hello-sensor
spec:
  dependencies:
    - name: http-event
      eventSourceName: http-event-source
      eventName: example
  triggers:
    - template:
        name: hello-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hello-argo-events-
              spec:
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: mrstask/argo-hello
                      imagePullPolicy: IfNotPresent
