apiVersion: v1
kind: Service
metadata:
  name: http-event-source-svc
  labels:
    app: http-event-source
spec:
  selector:
    app: http-event-source
  ports:
    - name: http
      port: 12000
      targetPort: http
