apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: 3-fantastic-bear-sensor
spec:
  template:
    serviceAccountName: sa-argo-workflow
  dependencies:
    - name: workflow-event
      eventSourceName: 2-fantastic-bear-watcher
      eventName: 2-fantastic-bear-succeeded
  triggers:
    - template:
        name: trigger-3-fantastic-bear
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: 3-fantastic-bear-
              spec:
                entrypoint: argosay
                arguments:
                  parameters:
                  - name: message
                    value: "hello from 3-fantastic-bear"
                workflowTemplateRef:
                  name: 3-fantastic-bear
                ttlStrategy:
                  secondsAfterCompletion: 300
